### ISSUE TITLE
Variable values not transferred to the variables.tf file

### ISSUE THREAD

**Issue by thomassuedbroecker** [cloud-native-toolkit/terraform-ibm-vpc-subnets#66]
Variables are not transferred to the variables.tf file
I want to create 1 subnet and not 3.

### Step 1: Create own BOM file

```yaml
kind: BillOfMaterial
metadata:
  name: my-bom
spec:
  modules:
    # Virtual Private Cloud
    - name: ibm-vpc
      variables:
      - name: ibm-vpc_name
        value: "tsued-gitops-sample"
    - name: ibm-vpc-subnets
      variables:
      - name: ibm-vpc-subnets__count
        value: 1
```

### Step 2: Use iascable to build the needed files

```sh
iascable build -i my-bom.yaml
```

### Step 3: Verify created bom.yaml file

It contains the wrong number or better doesn't use the right value for the variable.

```yaml
apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: my-bom
spec:
  modules:
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.16.0
      variables:
        - name: ibm-vpc_name
          value: tsued-gitops-sample
    - name: ibm-vpc-subnets
      alias: ibm-vpc-subnets
      version: v1.13.2
      variables:
        - name: ibm-vpc-subnets__count
          value: 1
    - name: ibm-resource-group
      alias: resource_group
      version: v3.2.16
  variables:
    - name: region
      type: string
      description: The IBM Cloud region where the cluster will be/has been installed.
    - name: ibmcloud_api_key
      type: string
    - name: ibm-vpc-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 3
    - name: resource_group_name
      type: string
      description: The name of the resource group
```

### Step 4: Verify created `variables.tf` file

It contains the wrong number or better doesn't use the right value for the variable.

```terraform
variable "ibm-vpc-subnets__count" {
  type = number
  description = "The number of subnets that should be provisioned"
  default = 3
}
```

### Step 5:  Verify the create evenvironment

The result is 3 subnets will be created and not 1.

**Comment by timroster** [comment]
@thomassuedbroecker the bom variables scoped at the module level should use the input names specified in the respective `module.yaml` file - not the fully expanded values expected in the final `variables.tf` file.

Try using something like:

```
kind: BillOfMaterial
metadata:
  name: my-bom
spec:
  modules:
    # Virtual Private Cloud
    - name: ibm-vpc
      variables:
      - name: name
        value: "tsued-gitops-sample"
    - name: ibm-vpc-subnets
      variables:
      - name: _count
        value: 1
 ```
 
 `iascable` will build this out to this BOM:
 
 ```
 kind: BillOfMaterial
metadata:
  name: my-bom
spec:
  modules:
    - name: ibm-vpc
      alias: ibm-vpc
      version: v1.16.0
      variables:
        - name: name
          value: tsued-gitops-sample
    - name: ibm-vpc-subnets
      alias: ibm-vpc-subnets
      version: v1.13.2
      variables:
        - name: _count
          value: 1
    - name: ibm-resource-group
      alias: resource_group
      version: v3.2.16
  variables:
    - name: region
      type: string
      description: The IBM Cloud region where the cluster will be/has been installed.
    - name: ibmcloud_api_key
      type: string
    - name: ibm-vpc-subnets__count
      type: number
      description: The number of subnets that should be provisioned
      defaultValue: 1
    - name: resource_group_name
      type: string
      description: The name of the resource group
```

And you would find that in the `output/my-bom/terraform/variables.tf` this:

```
...
variable "ibm-vpc-subnets__count" {
  type = number
  description = "The number of subnets that should be provisioned"
  default = 1
}
...
```
